# yaml file to test github actions

name: Node api testing

on:
  pull_request:
    branches: [ main ]

jobs:
  api_test:
    runs-on: ubuntu-latest
    env:
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        SOURCE_AMI: ${{ secrets.SOURCE_AMI }}
        SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
        DEFAULT_SUBNET_ID: ${{ secrets.DEFAULT_SUBNET_ID }}

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - run: zip -r webapp.zip *.js *.json
    - run: unzip -l webapp.zip
    - run: packer fmt -check packer/ami.pkr.hcl
    - run: packer validate packer/ami.pkr.hcl